# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # As per doc, pip covers a number of build tools, including poetry
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Without this, it will rebase upon each push, there is no way to turn it into periodic
    # (as of 2026-05-12)
    rebase-strategy: "disabled" 
