# Requires tests/ in PYTHONPATH
from resources.real_test_case.wf_mapping import (
	E2U_ENSEMBL_GENE_MAPPER, E2U_ENSEMBL_GENE_ACCESSION_MAPPERS,
	E2U_ENSEMBL_PROTEIN_MAPPER, E2U_UNIPROT_ACCESSION_MAPPERS,
	E2U_GENE2PROTEIN_MAPPER, NEO_LOADER_CONFIG
)

import resources.real_test_case.wf_config as wf_config

from ketl.io.core import pg_df_2_pg_jsonl, triples_2_pg_df
from ketl.spark.utils import df_check_path, df_path, create_spark_session_from_config, df_save
from ketl.config import load_config
from ketl.io.neoloader import create_neo_driver_from_config, pg_jsonl_neo_loader, async_pg_jsonl_neo_loader
from ketl.core import PGElementType

from pyspark.sql.functions import lit

import asyncio

# TODO: ketl logging

KETL_DATA = os.environ [ "KETL_DATA" ] # TODO
KETL_IN = os.path.abspath ( workflow.basedir )
KETL_OUT = f"{KETL_DATA}/output"
KETL_TMP = f"{KETL_DATA}/tmp"
my_dir = Path ( os.path.dirname ( __file__ ) ).absolute ()

# As said in wf_config, this is an alternative way to configure
# config = load_config ( my_dir / "config.yml" )
# spark_session = create_spark_session_from_config ( config.get ( "spark" ) )
# neo_driver = create_neo_driver_from_config ( config.get ( "neo4j" ) )
# neo_loader_config = NeoLoaderConfig.from_config ( config.get ( "neoloader" ) )

rule all:
	"""
	Loads the final JSONL file into Neo4j, using the NeoLoader.

	This just triggers the neo_loader rule for nodes and edges.
	"""
	input:
		expand ( f"{KETL_OUT}/knowledge-graph.done.{{pg_type}}", pg_type = [ "nodes", "edges" ] )


rule neo_loader:
	"""
	Loads the final JSONL file into Neo4j, using the NeoLoader.

	This loads nodes and edges with 2 separate rule instantiations, triggered by 
	the wildcard expansion in all.

	TODO: meh, this is too verbose, move the incremental logic to pg_jsonl_neo_loader()
	"""
	input:
		f"{KETL_OUT}/knowledge-graph.json"
	output:
		f"{KETL_OUT}/knowledge-graph.done.{{pg_type}}"
	run:
		n_nodes = pg_jsonl_neo_loader (
			pg_jsonl_source = input[0],
			done_base_path = output[0],
			neo_driver = wf_config.create_neo4j_driver (),
			do_nodes = wildcards.pg_type == "nodes",
			do_edges = wildcards.pg_type == "edges",
			config = NEO_LOADER_CONFIG
		)


rule triples_2_json_pg:
	"""
	Converts the PG DataFrame into JSONL, which is the format expected by the NeoLoader.
	"""
	input:
		df_check_path ( f"{KETL_TMP}/knowledge-graph.parquet" )
	output:
		f"{KETL_OUT}/knowledge-graph.json"
	run:
		pg_df_2_pg_jsonl ( input[0], wf_config.get_spark_session(), output[0] )


rule triples_2_pg_df:
	"""
	Builds a single PG DataFrame from multiple triples DataFrames.

	Doing some partial grouping of the various triple data frames generated by the mappers is 
	one of the reasonable way to organise a workflow.

	If you have very big triple DFs, you might want to split this into further rules.
	"""
	input:
		# The PG builder needs to distinguish between nodes and edges, see below
		nodes = [
			df_check_path ( f"{KETL_TMP}/gene-triples.parquet" ),
			df_check_path ( f"{KETL_TMP}/gene-accession-triples.parquet" ),
			df_check_path ( f"{KETL_TMP}/protein-triples.parquet" ),
			df_check_path ( f"{KETL_TMP}/protein-accession-triples.parquet" )
		],
		edges = [
			df_check_path ( f"{KETL_TMP}/gene-accession-links-triples.parquet" ),
			df_check_path ( f"{KETL_TMP}/protein-accession-links-triples.parquet" ),
			df_check_path ( f"{KETL_TMP}/gene2protein.parquet" )
		]
	output:
		df_check_path ( f"{KETL_TMP}/knowledge-graph.parquet" )
	run:
		# Work out nodes together and then edge together
		# TODO: it sucks, move it to an helper receiving the path array and PG type
		pg_df = None
		spark_session = wf_config.get_spark_session()
		for paths, pg_type in (input.nodes, PGElementType.NODE), (input.edges, PGElementType.EDGE):
			triples_df = None
			for path in paths:
				path = df_path ( path ) # from the check path to the actual path
				this_df = spark_session.read.parquet ( path )
				triples_df = \
					this_df if not triples_df else triples_df.unionByName ( this_df )

			# This can get a Parquet path and save, but here we combine nodes and edges and 
			# save at the end
			this_pg_df = triples_2_pg_df ( triples_df, pg_type, spark = spark_session )

			# If it is a node DF, it needs empty columns about 'from' and 'to', 
			# so that the union with edge DFs works.
			# TODO: ABSOLUTELY to move to some utility!
			if pg_type == PGElementType.NODE:
				this_pg_df = this_pg_df.withColumn ( "from", lit ( None ) )\
				  .withColumn ( "to", lit ( None ) )

			pg_df = this_pg_df if pg_df is None else pg_df.unionByName ( this_pg_df )
		
		# As said above
		df_save ( pg_df, output[0] )



rule map_ensembl_plants_genes:
	"""
	Maps the TSV input to gene node triples and other related PG triples, such as accession
	nodes and edges.
	"""
	input:
		f"{KETL_IN}/ensmbl-uniprot-genes.tsv"
	output:
		df_check_path ( f"{KETL_TMP}/gene-triples.parquet" ),
		df_check_path ( f"{KETL_TMP}/gene-accession-triples.parquet" ),
		df_check_path ( f"{KETL_TMP}/gene-accession-links-triples.parquet" )
	run:
		# TODO: blah, move it to an helper getting input, list[mapper, out_path]
		#
		spark_session = wf_config.get_spark_session()
		E2U_ENSEMBL_GENE_MAPPER.map ( spark_session, input[0], out_path = output[0] )
		# These have node/edge mappers
		E2U_ENSEMBL_GENE_ACCESSION_MAPPERS [ 0 ].map ( spark_session, input[0], out_path = output[1] )
		E2U_ENSEMBL_GENE_ACCESSION_MAPPERS [ 1 ].map ( spark_session, input[0], out_path = output[2] )


rule map_ensembl_plants_proteins:
	"""
	Maps the TSV input to protein triples and other related PG triples, such as accession 
	nodes and edges.
	"""
	input:
		f"{KETL_IN}/ensmbl-uniprot-genes.tsv"
	output:
		df_check_path ( f"{KETL_TMP}/protein-triples.parquet" ),
		df_check_path ( f"{KETL_TMP}/protein-accession-triples.parquet" ),
		df_check_path ( f"{KETL_TMP}/protein-accession-links-triples.parquet" )

	run:
		spark_session = wf_config.get_spark_session()
		E2U_ENSEMBL_PROTEIN_MAPPER.map ( spark_session, input[0], out_path = output[0] )
		E2U_UNIPROT_ACCESSION_MAPPERS [ 0 ].map ( spark_session, input[0], out_path = output[1] )
		E2U_UNIPROT_ACCESSION_MAPPERS [ 1 ].map ( spark_session, input[0], out_path = output[2] )


rule map_ensembl_plants_encodes:
	"""
	Maps the TSV input to gene-to-protein triples.
	"""
	input:
		f"{KETL_IN}/ensmbl-uniprot-genes.tsv"
	output:
		df_check_path ( f"{KETL_TMP}/gene2protein.parquet" )
	run:
		spark_session = wf_config.get_spark_session()
		E2U_GENE2PROTEIN_MAPPER.map ( spark_session, input[0], out_path = output[0] )
